import manifest from './gallery-images.json'

export interface GalleryImage {
  src: string
  alt: string
  /** Explicit original dimensions to set the aspect ratio and prevent layout shift. */
  width?: number
  height?: number
}

export interface Gallery {
  /** Exact URL path, preserved from Squarespace, e.g. /2022 or /past-work */
  path: string
  title: string
  description?: string
  images: GalleryImage[]
  /** Canonical path, when this gallery is an alias of another (e.g. /past-work → /2022). */
  canonicalPath?: string
}

// Image lists are generated by scripts/download-galleries.mjs (pulled from the live
// Squarespace site into /public/images/<folder>/). Keyed by folder name here.
const images = manifest as Record<string, GalleryImage[]>

// Gallery photos are served from Cloudflare R2 via this custom domain (Phase 9),
// so they're never committed to the repo. Blog images stay root-relative (in-repo).
const IMAGES_BASE = 'https://images.cailinpitt.com'

/** Resolve a manifest image path (e.g. /images/2022/x.jpg) to its served R2 URL. */
export const imageUrl = (src: string) => IMAGES_BASE + src

export const galleries: Gallery[] = [
  { path: '/2022', title: '2022', images: images['2022'] },
  { path: '/2021', title: '2021', images: images['2021'] },
  { path: '/2020', title: '2020', images: images['2020'] },
  { path: '/2019', title: '2019', images: images['2019'] },
  { path: '/2018', title: '2018', images: images['2018'] },
  { path: '/latest-work', title: '2017', images: images['latest-work'] },
  { path: '/latest', title: '2016', images: images['latest'] },
  { path: '/2015', title: '2015', images: images['2015'] },
  { path: '/2014', title: '2014', images: images['2014'] },
  // /past-work historically redirected to /2022; keep the URL working as an alias.
  { path: '/past-work', title: 'Past Work', images: images['2022'], canonicalPath: '/2022' },
]
