// Generated by Wrangler by running `wrangler types`

interface Env {
	TZ_OFFSET_SECONDS: "-18000";
	ALLOWED_ORIGIN: "https://cailinpitt.com";
	GITHUB_REPO: "cailinpitt/cailinpitt.com";
	IMAGES: R2Bucket;
	DB: D1Database;
}
