// Generated by Wrangler by running `wrangler types`

interface Env {
	TZ_OFFSET_SECONDS: "-18000";
	ALLOWED_ORIGIN: "https://cailinpitt.com";
	TURNSTILE_SITE_KEY: "1x00000000000000000000AA";
	TURNSTILE_SECRET: string;
	ADMIN_TOKEN: string;
	IP_SALT: string;
	DB: D1Database;
}
