// Generated by Wrangler by running `wrangler types`

interface Env {
	ALLOWED_ORIGIN: "https://cailinpitt.com";
	TURNSTILE_SITE_KEY: "0x4AAAAAAEEBNcQ83mO9Fcud";
	TURNSTILE_SECRET: string;
	ADMIN_TOKEN: string;
	IP_SALT: string;
	DB: D1Database;
}
