// Generated by Wrangler by running `wrangler types`

interface Env {
	TZ_OFFSET_SECONDS: "-18000";
	ALLOWED_ORIGIN: "https://cailinpitt.com";
	MIRROR_BUDGET: "18";
	DB: D1Database;
	IMAGES: R2Bucket;
}
