// The Letterboxd diary feed.
//
// Letterboxd's API is still invite-only beta (api@letterboxd.com), but every
// member profile publishes an RSS feed, and for a diary it carries everything
// this page needs in *named* fields — rating, watched date, rewatch flag, TMDB
// id, poster. So this is not scraping: nothing here depends on
// markup or class names, only on a namespaced feed Letterboxd publishes on
// purpose. A redesign of the site cannot break it.
//
//   <item>
//     <title>Office Space, 1999 - ★★★½</title>
//     <link>https://letterboxd.com/USER/film/office-space/</link>
//     <guid isPermaLink="false">letterboxd-watch-1388436545</guid>
//     <pubDate>Fri, 10 Jul 2026 04:55:16 +1200</pubDate>
//     <letterboxd:watchedDate>2026-07-09</letterboxd:watchedDate>
//     <letterboxd:rewatch>No</letterboxd:rewatch>
//     <letterboxd:filmTitle>Office Space</letterboxd:filmTitle>
//     <letterboxd:filmYear>1999</letterboxd:filmYear>
//     <letterboxd:memberRating>3.5</letterboxd:memberRating>
//     <letterboxd:memberLike>Yes</letterboxd:memberLike>
//     <tmdb:movieId>1339713</tmdb:movieId>
//     <description><![CDATA[ <p><img src="…poster.jpg"/></p> <p>review…</p> ]]></description>
//   </item>
//
// Review bodies are deliberately dropped rather than stored: the page shows
// ratings only. Same for the entry's permalink, which is under /<member>/ and
// would put the account name in the API and on every card.
//
// ## Two things to know
//
// The feed is a 50-entry window, which is why the sync upserts instead of
// replacing (see schema.sql) and why there is a CSV backfill path for the
// history behind it (see scripts/watching-backfill.mjs).
//
// And Letterboxd 403s requests that don't look like a browser — the `accept`
// and `user-agent` below are load-bearing, not decoration. If they ever block
// Cloudflare egress by IP rather than by agent, this Worker starts returning
// FeedError, and the fix is to move this fetch into the GitHub Action that
// already runs on a schedule: parse there, and write the rows the same way
// scripts/watching-backfill.mjs does. The storage half needs no changes.

/** Give up rather than hold the invocation open on a slow origin. */
const TIMEOUT_MS = 10_000

/** A feed of 50 entries with reviews runs ~80KB; this is pure paranoia. */
const MAX_BYTES = 4 * 1024 * 1024

export interface DiaryEntry {
  /** `<slug>|<watched_date>` — see the note on films.id in schema.sql. */
  id: string
  guid: string | null
  title: string
  year: number | null
  slug: string | null
  watchedDate: string
  rewatch: boolean
  rating: number | null
  liked: boolean
  tmdbId: number | null
  posterSource: string | null
  publishedAt: number | null
}

/** Thrown for anything that isn't a parseable 200, so /sync can report it. */
export class FeedError extends Error {}

export async function fetchDiary(username: string): Promise<DiaryEntry[]> {
  const url = `https://letterboxd.com/${encodeURIComponent(username)}/rss/`
  const res = await fetch(url, {
    headers: {
      accept: 'application/rss+xml, application/xml;q=0.9, */*;q=0.8',
      // Deliberately a real browser string. A descriptive bot agent gets a 403
      // here — verified against letterboxd.com — and a 403 that looked like a
      // parse failure would be a genuinely confusing thing to debug later.
      'user-agent':
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36',
    },
    signal: AbortSignal.timeout(TIMEOUT_MS),
  })
  if (!res.ok) throw new FeedError(`letterboxd rss ${res.status} for ${username}`)

  const body = await res.text()
  if (body.length > MAX_BYTES) throw new FeedError('letterboxd rss: feed too large')
  if (!body.includes('<rss')) throw new FeedError('letterboxd rss: not a feed')

  return parseDiary(body)
}

// ---- parsing -------------------------------------------------------------
//
// Regex rather than a parser, matching how the rest of this site reads small
// known XML (see scripts/generate-atproto.mjs). There is no DOMParser in
// Workers, and pulling in a dependency to read six fixed tags would be a poor
// trade. The feed is machine-generated by one publisher, so the shapes below
// are the only shapes that occur.

const ITEM = /<item>([\s\S]*?)<\/item>/g

/** Text of the first `<tag>`, CDATA unwrapped and entities decoded. */
function tag(item: string, name: string): string | null {
  const match = item.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)</${name}>`))
  if (!match) return null
  const raw = match[1].replace(/^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/, '$1')
  const text = decode(raw).trim()
  return text || null
}

const ENTITIES: Record<string, string> = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  '#39': "'",
  nbsp: ' ',
}

function decode(text: string): string {
  return text.replace(/&(#x?[0-9a-f]+|[a-z]+);/gi, (whole, code: string) => {
    const named = ENTITIES[code.toLowerCase()]
    if (named) return named
    if (code[0] === '#') {
      const point = code[1] === 'x' || code[1] === 'X' ? parseInt(code.slice(2), 16) : Number(code.slice(1))
      return Number.isFinite(point) && point > 0 && point <= 0x10ffff ? String.fromCodePoint(point) : whole
    }
    return whole
  })
}

/**
 * The film slug from a diary permalink.
 *
 * `https://letterboxd.com/USER/film/office-space/` → `office-space`, and a
 * rewatch's `…/office-space/1/` → `office-space` too: the trailing index counts
 * the viewing, not the film, and folding it in would file one film under two
 * ids. The date in the primary key is what separates the viewings.
 */
function slugFrom(link: string | null): string | null {
  if (!link) return null
  const match = link.match(/\/film\/([^/]+)\//)
  return match ? match[1] : null
}

/** The poster is the first <img> in the description, if the entry has one. */
function posterFrom(description: string | null): string | null {
  const src = description?.match(/<img[^>]+src="([^"]+)"/i)?.[1]
  if (!src) return null
  // Only Letterboxd's own CDN. This url is fetched by the mirror and its bytes
  // end up on the site's origin, so it is not a value to take on faith from a
  // field a redesign could repoint.
  return /^https:\/\/[a-z0-9.-]*ltrbxd\.com\//i.test(src) ? src : null
}

const num = (value: string | null): number | null => {
  if (value == null) return null
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : null
}

export function parseDiary(xml: string): DiaryEntry[] {
  const entries: DiaryEntry[] = []

  for (const [, item] of xml.matchAll(ITEM)) {
    // The same feed carries list updates and (for some members) stories, which
    // have no watchedDate. That field is what makes an item a diary entry, so
    // it doubles as the filter — no guid-prefix sniffing required.
    const watchedDate = tag(item, 'letterboxd:watchedDate')
    if (!watchedDate || !/^\d{4}-\d{2}-\d{2}$/.test(watchedDate)) continue

    const link = tag(item, 'link')
    const slug = slugFrom(link)
    const title = tag(item, 'letterboxd:filmTitle')
    if (!title) continue

    const description = item.match(/<description>([\s\S]*?)<\/description>/)?.[1] ?? null
    const cdata = description?.replace(/^\s*<!\[CDATA\[([\s\S]*?)\]\]>\s*$/, '$1') ?? null
    const published = tag(item, 'pubDate')
    const publishedAt = published ? Date.parse(published) : NaN
    const rating = num(tag(item, 'letterboxd:memberRating'))

    entries.push({
      // Falling back to the title keeps an entry whose permalink shape changed
      // out of a single colliding `|date` bucket with every other such entry.
      id: `${slug ?? title.toLowerCase().replace(/[^a-z0-9]+/g, '-')}|${watchedDate}`,
      guid: tag(item, 'guid'),
      title,
      year: num(tag(item, 'letterboxd:filmYear')),
      slug,
      watchedDate,
      rewatch: tag(item, 'letterboxd:rewatch') === 'Yes',
      // Letterboxd rates in half stars, 0.5–5. Anything else is a field that
      // changed meaning, and dropping it beats rendering six stars.
      rating: rating != null && rating > 0 && rating <= 5 ? rating : null,
      liked: tag(item, 'letterboxd:memberLike') === 'Yes',
      tmdbId: num(tag(item, 'tmdb:movieId')),
      posterSource: posterFrom(cdata),
      publishedAt: Number.isFinite(publishedAt) ? Math.floor(publishedAt / 1000) : null,
    })
  }

  // Newest first regardless of how the feed happens to order itself, and
  // last-write-wins on a duplicate id (two viewings of one film on one day).
  const byId = new Map(entries.map((entry) => [entry.id, entry]))
  return [...byId.values()].sort((a, b) => b.watchedDate.localeCompare(a.watchedDate))
}
