// Generated by Wrangler by running `wrangler types`

interface Env {
	KV: KVNamespace;
	LASTFM_USER: "ticketmasterceo";
	TZ_OFFSET_SECONDS: "-18000";
	ALLOWED_ORIGIN: "https://cailinpitt.com,http://localhost:5173";
	DB: D1Database;
}
